version: '3.8'
services:
  
  connector:
    image: connector
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - ./data:/data